# Generated by Django 4.2.7 on 2024-04-16 06:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("specialization", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferDoctor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("doctor_name", models.CharField(max_length=100)),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_number",
                                message="Must be a 10-digit number",
                                regex="^[0-9]{10}$",
                            )
                        ],
                    ),
                ),
                (
                    "specialization_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="specialization.specialization",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
