# Generated by Django 4.2.7 on 2023-11-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symptom_name', models.CharField(max_length=50)),
            ],
        ),
    ]
