# Generated by Django 4.2.7 on 2024-01-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom_master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptommaster',
            name='symptom_name',
            field=models.CharField(max_length=80),
        ),
    ]
