# Generated by Django 4.2.7 on 2024-02-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom_master', '0002_alter_symptommaster_symptom_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptommaster',
            name='symptom_name',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
