# Generated by Django 4.2.7 on 2023-11-27 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procedure', '0001_initial'),
        ('specialization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecializationProcedureMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('procedure_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='procedure.procedure')),
                ('specialization_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='specialization.specialization')),
            ],
        ),
    ]
