# Generated by Django 4.2.7 on 2024-04-19 11:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VisitorContact",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("visitor_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, null=True)),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_number",
                                message="Must be a 10-digit number",
                                regex="^[0-9]{10}$",
                            )
                        ],
                    ),
                ),
                ("country", models.CharField(max_length=100, null=True)),
                ("state", models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
