# Generated by Django 4.2.7 on 2024-03-04 09:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("doctor_receptionist_mapping", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="doctorreceptionistmapping",
            unique_together={("doctor_data", "receptionist_data")},
        ),
    ]
