# Generated by Django 4.2.7 on 2024-04-03 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("fee_structure", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeeType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="userfeestructure",
            name="fee_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="fee_structure.feetype",
            ),
        ),
    ]
