# Generated by Django 4.2.7 on 2024-04-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fee_structure", "0002_feetype_alter_userfeestructure_fee_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feetype",
            name="name",
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
    ]
