# Generated by Django 4.2.7 on 2024-04-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fee_structure", "0003_alter_feetype_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfeestructure",
            name="cost_type",
            field=models.CharField(
                choices=[("DF", "DOCTOR_FEE"), ("SC", "SEVICE_CHARGE")],
                default="DF",
                max_length=2,
            ),
        ),
    ]
