# Generated by Django 4.2.7 on 2023-11-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatemaster',
            name='template_path',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
