# Generated by Django 4.2.7 on 2024-02-09 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investigation_master', '0001_initial'),
        ('medicine_master', '0003_medicinemaster_medicine_modality_and_more'),
        ('template_master', '0002_templatemaster_template_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatemaster',
            name='investigation_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='investigation_master.investigationmaster'),
        ),
        migrations.AddField(
            model_name='templatemaster',
            name='medicine_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='medicine_master.medicinemaster'),
        ),
        migrations.AddField(
            model_name='templatemaster',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
