# Generated by Django 4.2.7 on 2024-03-22 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("investigation_master", "0001_initial"),
        ("medicine_master", "0008_alter_medicinemaster_medicine_dosage"),
        ("template_master", "0003_templatemaster_investigation_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="templatemaster",
            name="investigation_id",
        ),
        migrations.RemoveField(
            model_name="templatemaster",
            name="medicine_id",
        ),
        migrations.RemoveField(
            model_name="templatemaster",
            name="template_path",
        ),
        migrations.AddField(
            model_name="templatemaster",
            name="template_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="templatemaster",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("IS", "INVESTIGATION_SET"),
                    ("MS", "MEDICINE_SET"),
                    ("VS", "VITAL_SET"),
                ],
                default="MS",
                max_length=2,
            ),
        ),
        migrations.CreateModel(
            name="MedicineSet",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "medicine_dosage",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=2, null=True
                    ),
                ),
                (
                    "medicine_timing",
                    models.CharField(
                        choices=[
                            ("MN", "MORNING"),
                            ("MD", "MIDDAY"),
                            ("NN", "NOON"),
                            ("AF", "AFTERNOON"),
                            ("EV", "EVENING"),
                            ("NT", "NIGHT"),
                        ],
                        default="MN",
                        max_length=2,
                    ),
                ),
                (
                    "medicine_modality",
                    models.CharField(
                        choices=[("AF", "AFTER_FOOD"), ("BF", "BEFORE_FOOD")],
                        default="AF",
                        max_length=2,
                    ),
                ),
                (
                    "medicine_duration",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "medicine_instruction",
                    models.TextField(blank=True, max_length=200, null=True),
                ),
                (
                    "collection_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="template_master.templatemaster",
                    ),
                ),
                (
                    "medicine_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="medicine_master.medicinemaster",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvestigationSet",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("note", models.TextField(blank=True, max_length=250, null=True)),
                (
                    "collection_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="template_master.templatemaster",
                    ),
                ),
                (
                    "investigation_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="investigation_master.investigationmaster",
                    ),
                ),
            ],
        ),
    ]
