# Generated by Django 4.2.7 on 2024-03-25 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("template_master", "0004_remove_templatemaster_investigation_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investigationset",
            name="collection_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="investigation_sets",
                to="template_master.templatemaster",
            ),
        ),
        migrations.AlterField(
            model_name="medicineset",
            name="collection_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="medicine_sets",
                to="template_master.templatemaster",
            ),
        ),
    ]
