# Generated by Django 4.2.7 on 2024-04-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("template_master", "0006_alter_medicineset_medicine_modality"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicineset",
            name="medicine_dosage",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="medicineset",
            name="medicine_duration",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="medicineset",
            name="medicine_instruction",
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="medicineset",
            name="medicine_modality",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AF", "AFTER_FOOD"),
                    ("BF", "BEFORE_FOOD"),
                    ("WF", "WITH_FOOD"),
                ],
                default="AF",
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="medicineset",
            name="medicine_timing",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
