# Generated by Django 4.2.7 on 2024-04-09 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("booking_slot", "0002_alter_bookingslot_unique_together_daygroup_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="daygroup",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="bookingslot",
            name="doctor_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="bookingslot",
            name="day_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking_slots",
                to="booking_slot.daygroup",
            ),
        ),
        migrations.AlterField(
            model_name="bookingslot",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="daygroup",
            name="days",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="daygroup",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="daygroup",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name="bookingslot",
            unique_together={("doctor_id", "day_group")},
        ),
        migrations.RemoveField(
            model_name="daygroup",
            name="doctor_id",
        ),
    ]
