# Generated by Django 4.2.7 on 2024-04-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking_slot", "0004_daygroup_doctor_id_alter_daygroup_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingslot",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="daygroup",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
