# Generated by Django 4.2.7 on 2024-04-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking_slot", "0005_alter_bookingslot_id_alter_daygroup_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="bookingslot",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="bookingslot",
            name="day",
            field=models.CharField(
                choices=[
                    ("mon", "Monday"),
                    ("tue", "Tuesday"),
                    ("wed", "Wednesday"),
                    ("thu", "Thursday"),
                    ("fri", "Friday"),
                    ("sat", "Saturday"),
                    ("sun", "Sunday"),
                ],
                default="mon",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="bookingslot",
            name="afternoon_slots_is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="bookingslot",
            name="evening_slots_is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="bookingslot",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="bookingslot",
            name="morning_slots_is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name="bookingslot",
            name="day_group",
        ),
    ]
