# Generated by Django 4.2.7 on 2024-04-13 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("booking_slot", "0007_bookingslot_doctor_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Slot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("morning", "Morning"),
                            ("afternoon", "Afternoon"),
                            ("evening", "Evening"),
                        ],
                        max_length=9,
                    ),
                ),
                ("slot_number", models.IntegerField()),
                ("is_booked", models.BooleanField(default=False)),
                (
                    "booking_slot",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="individual_slots",
                        to="booking_slot.bookingslot",
                    ),
                ),
            ],
            options={
                "unique_together": {("booking_slot", "session_type", "slot_number")},
            },
        ),
    ]
