# Generated by Django 4.2.7 on 2024-04-13 07:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("booking_slot", "0008_slot"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BookingSlot",
            new_name="BookingSlotConfig",
        ),
    ]
