# Generated by Django 4.2.7 on 2024-04-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking_slot", "0009_rename_bookingslot_bookingslotconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="slot",
            name="date",
            field=models.DateField(null=True),
        ),
    ]
