# Generated by Django 4.2.7 on 2024-04-15 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("booking_slot", "0011_rename_booking_slot_slot_booking_config_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="daygroup",
            name="days",
        ),
        migrations.AddField(
            model_name="bookingslotconfig",
            name="day_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking_slots",
                to="booking_slot.daygroup",
            ),
        ),
        migrations.AddField(
            model_name="daygroup",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name="bookingslotconfig",
            unique_together={("day_group", "day")},
        ),
        migrations.RemoveField(
            model_name="bookingslotconfig",
            name="doctor_id",
        ),
    ]
