# Generated by Django 4.2.7 on 2024-04-08 07:26

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):
    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("saved_patient", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="savedpatient",
            name="tag",
        ),
        migrations.AddField(
            model_name="savedpatient",
            name="tag",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
