# Generated by Django 4.2.7 on 2024-04-08 13:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("saved_patient", "0003_alter_savedpatient_tag"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="savedpatient",
            unique_together={("doctor_id", "patient_id")},
        ),
    ]
