# Generated by Django 4.2.7 on 2024-02-09 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investigation_master', '0001_initial'),
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationInvestigation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('consultation_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consultation.consultation')),
                ('investigation_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investigation_master.investigationmaster')),
            ],
        ),
    ]
