# Generated by Django 4.2.7 on 2024-02-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultation_investigation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultationinvestigation",
            name="note",
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
