# Generated by Django 4.2.7 on 2023-11-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('CL', 'CLINIC'), ('PL', 'POLYCLINIC'), ('HS', 'HOSPITAL')], default='PT', max_length=2)),
            ],
        ),
    ]
