# Generated by Django 4.2.7 on 2024-01-31 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specialization', '0001_initial'),
        ('appointment', '0001_initial'),
        ('vital_master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientVital',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vital_value', models.FloatField(null=True)),
                ('appointment_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appointment.appointment')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('specialization_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='specialization.specialization')),
                ('vital_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vital_master.vitalmaster')),
            ],
        ),
    ]
