# Generated by Django 4.2.7 on 2024-03-20 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("specialization", "0001_initial"),
        ("patient_vital", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientvital",
            name="specialization_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="specialization.specialization",
            ),
        ),
        migrations.AlterField(
            model_name="patientvital",
            name="vital_value",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
