# Generated by Django 4.2.7 on 2024-01-31 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specialization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_datetime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CR', 'CREATED'), ('IP', 'IN_PROGRESS'), ('CN', 'CANCELLED'), ('PP', 'POSTPONED'), ('CL', 'CLOSED')], default='CR', max_length=2)),
                ('doctor_id', models.IntegerField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=50)),
                ('next_appointment', models.DateTimeField(blank=True, null=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('specialization_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='specialization.specialization')),
            ],
            options={
                'ordering': ['created'],
                'indexes': [models.Index(fields=['created'], name='appointment_created_c85fda_idx')],
            },
        ),
    ]
