# Generated by Django 4.2.7 on 2024-03-20 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("specialization", "0001_initial"),
        ("appointment", "0007_appointment_follow_up_date_appointment_refer_to"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="refer_to",
        ),
        migrations.AddField(
            model_name="appointment",
            name="refer_doctor",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="appointment",
            name="refer_specilization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specialization_followup",
                to="specialization.specialization",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="specialization_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="doctor_specialization",
                to="specialization.specialization",
            ),
        ),
    ]
