# Generated by Django 4.2.7 on 2024-03-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "appointment",
            "0008_remove_appointment_refer_to_appointment_refer_doctor_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="refer_doctor",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
