# Generated by Django 4.2.7 on 2024-03-20 09:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("appointment", "0009_alter_appointment_refer_doctor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment",
            old_name="refer_specilization",
            new_name="refer_specialization",
        ),
    ]
