# Generated by Django 4.2.7 on 2024-03-21 08:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "appointment",
            "0010_rename_refer_specilization_appointment_refer_specialization",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="refer_specialization",
        ),
    ]
