# Generated by Django 4.2.7 on 2024-04-08 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("booking_slot", "0001_initial"),
        ("appointment", "0011_remove_appointment_refer_specialization"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="booking_slot",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="booking_slot.bookingslot",
            ),
        ),
    ]
