# Generated by Django 4.2.7 on 2024-04-13 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("booking_slot", "0008_slot"),
        ("appointment", "0012_appointment_booking_slot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="booking_slot",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointment_booked",
                to="booking_slot.slot",
            ),
        ),
    ]
