# Generated by Django 4.2.7 on 2024-02-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_symptom', '0002_alter_consultationsymptom_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationsymptom',
            name='duration',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationsymptom',
            name='severity',
            field=models.CharField(choices=[('MLD', 'MILD'), ('MED', 'MEDIUM'), ('SEV', 'SEVERE')], default='MLD', max_length=3),
        ),
    ]
