# Generated by Django 4.2.7 on 2024-05-01 05:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultation_symptom", "0004_alter_consultationsymptom_severity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultationsymptom",
            name="severity",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
