# Generated by Django 4.2.7 on 2023-11-28 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflow', '0001_initial'),
        ('component', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowComponentMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('component_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='component.component')),
                ('workflow_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflow.workflow')),
            ],
        ),
    ]
