# Generated by Django 4.2.7 on 2024-01-31 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entity', '0005_remove_entity_aadhar'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEntityMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('from_date', models.DateField(auto_now=True)),
                ('to_date', models.DateField(blank=True)),
                ('updated', models.DateField(auto_now_add=True)),
                ('entity_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entity.entity')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
