# Generated by Django 4.2.7 on 2024-01-31 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationInstruction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('instruction', models.TextField(blank=True, max_length=500)),
                ('consultation_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consultation.consultation')),
            ],
        ),
    ]
