# Generated by Django 4.2.7 on 2023-11-28 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specialization', '0001_initial'),
        ('entity', '0002_alter_entity_id_alter_entity_postal_code'),
        ('workflow', '0001_initial'),
        ('component', '0001_initial'),
        ('role', '0003_alter_role_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('component_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='component.component')),
                ('entity_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entity.entity')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='role.role')),
                ('specialization_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='specialization.specialization')),
                ('workflow_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflow.workflow')),
            ],
        ),
    ]
