# Generated by Django 4.2.7 on 2024-01-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VitalMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vital_name', models.CharField(max_length=100)),
                ('vital_unit', models.CharField(max_length=30)),
            ],
        ),
    ]
