# Generated by Django 4.2.7 on 2023-11-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('PT', 'PATIENT'), ('EA', 'ENTITY_ADMIN'), ('DR', 'DOCTOR')], default='PT', max_length=2),
        ),
    ]
