# Generated by Django 4.2.7 on 2023-11-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('PT', 'PATIENT'), ('EA', 'ENTITY_ADMIN'), ('DR', 'DOCTOR'), ('RC', 'RECEPTIONIST')], default='PT', max_length=2),
        ),
    ]
