# Generated by Django 4.2.7 on 2023-12-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0003_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
