# Generated by Django 4.2.7 on 2023-11-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('growth_required', models.BooleanField(default=False)),
                ('vital_required', models.BooleanField(default=False)),
            ],
        ),
    ]
