# Generated by Django 4.2.7 on 2024-02-29 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("consultation", "0006_remove_consultation_medicine_fingerprint_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedNote",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "note_type",
                    models.CharField(
                        choices=[("FND", "FINDING"), ("DGN", "DIAGNOSTIC")],
                        default="FND",
                        max_length=3,
                    ),
                ),
                ("title", models.TextField(max_length=255, null=True)),
                ("note", models.TextField(max_length=255, null=True)),
                (
                    "consultation_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="consultation.consultation",
                    ),
                ),
                (
                    "user_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
