# Generated by Django 4.2.7 on 2024-02-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("saved_note", "0002_alter_savednote_consultation_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savednote",
            name="note_type",
            field=models.CharField(
                choices=[("FND", "FINDING"), ("DGN", "DIAGNOSIS")],
                default="FND",
                max_length=3,
            ),
        ),
    ]
