# Generated by Django 4.2.7 on 2023-11-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine_Master',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(max_length=50)),
                ('medicine_dosage', models.CharField(max_length=50)),
            ],
        ),
    ]
