# Generated by Django 4.2.7 on 2023-11-26 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_master', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Medicine_Master',
            new_name='MedicineMaster',
        ),
    ]
