# Generated by Django 4.2.7 on 2024-02-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_master', '0002_rename_medicine_master_medicinemaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinemaster',
            name='medicine_modality',
            field=models.CharField(choices=[('AF', 'AFTER_FOOD'), ('BF', 'BEFORE_FOOD'), ('WF', 'WITH_FOOD'), ('EA', 'EMPTY_STOMACH')], default='CR', max_length=2),
        ),
        migrations.AddField(
            model_name='medicinemaster',
            name='medicine_timing',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
