# Generated by Django 4.2.7 on 2024-02-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_master', '0003_medicinemaster_medicine_modality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinemaster',
            name='medicine_modality',
            field=models.CharField(choices=[('AF', 'AFTER_FOOD'), ('BF', 'BEFORE_FOOD'), ('WF', 'WITH_FOOD'), ('EA', 'EMPTY_STOMACH')], default='AF', max_length=2),
        ),
    ]
