# Generated by Django 4.2.7 on 2024-02-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_master', '0006_alter_medicinemaster_medicine_modality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinemaster',
            name='medicine_modality',
        ),
        migrations.RemoveField(
            model_name='medicinemaster',
            name='medicine_timing',
        ),
        migrations.AddField(
            model_name='medicinemaster',
            name='medicine_form',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
