# Generated by Django 4.2.7 on 2024-02-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medicine_master", "0007_remove_medicinemaster_medicine_modality_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicinemaster",
            name="medicine_dosage",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
