# Generated by Django 4.2.7 on 2024-02-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_medicine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultationmedicine',
            old_name='medicine_timing_food',
            new_name='medicine_modality',
        ),
        migrations.AddField(
            model_name='consultationmedicine',
            name='medicine_duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
