# Generated by Django 4.2.7 on 2024-02-16 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_medicine', '0002_rename_medicine_timing_food_consultationmedicine_medicine_modality_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultationmedicine',
            old_name='instruction',
            new_name='medicine_instruction',
        ),
    ]
