# Generated by Django 4.2.7 on 2024-02-20 06:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("medicine_master", "0008_alter_medicinemaster_medicine_dosage"),
        ("consultation", "0002_consultation_diagnosis_consultation_finding"),
        (
            "consultation_medicine",
            "0003_rename_instruction_consultationmedicine_medicine_instruction",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="consultationmedicine",
            unique_together={("consultation_id", "medicine_id")},
        ),
    ]
