# Generated by Django 4.2.7 on 2024-02-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultation_medicine", "0004_alter_consultationmedicine_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultationmedicine",
            name="medicine_dosage",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=2, null=True
            ),
        ),
    ]
