# Generated by Django 4.2.7 on 2024-03-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultation_medicine", "0005_alter_consultationmedicine_medicine_dosage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultationmedicine",
            name="medicine_instruction",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
