# Generated by Django 4.2.7 on 2024-04-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "consultation_medicine",
            "0006_alter_consultationmedicine_medicine_instruction",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultationmedicine",
            name="medicine_duration",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="consultationmedicine",
            name="medicine_instruction",
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="consultationmedicine",
            name="medicine_modality",
            field=models.CharField(
                choices=[
                    ("AF", "AFTER_FOOD"),
                    ("BF", "BEFORE_FOOD"),
                    ("WF", "WITH_FOOD"),
                ],
                default="AF",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="consultationmedicine",
            name="medicine_timing",
            field=models.CharField(default="MN", max_length=100),
        ),
    ]
