# Generated by Django 4.2.7 on 2024-04-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "consultation_medicine",
            "0007_alter_consultationmedicine_medicine_duration_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultationmedicine",
            name="medicine_timing",
            field=models.CharField(max_length=100),
        ),
    ]
