# Generated by Django 4.2.7 on 2024-04-17 03:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultation_medicine", "0008_alter_consultationmedicine_medicine_timing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultationmedicine",
            name="medicine_dosage",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
