# Generated by Django 4.2.7 on 2024-04-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultation_medicine", "0009_alter_consultationmedicine_medicine_dosage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultationmedicine",
            name="medicine_modality",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AF", "AFTER_FOOD"),
                    ("BF", "BEFORE_FOOD"),
                    ("WF", "WITH_FOOD"),
                ],
                default="AF",
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="consultationmedicine",
            name="medicine_timing",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
