# Generated by Django 4.2.7 on 2024-01-25 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('role', '0004_alter_role_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoleMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='role.role')),
            ],
        ),
    ]
