# Generated by Django 4.2.7 on 2024-04-24 04:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PrescriptionSetting",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("doctor_info_is_visible", models.BooleanField()),
                (
                    "doctor_name",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "doctor_qualification",
                    models.CharField(blank=True, max_length=280, null=True),
                ),
                (
                    "registration_number",
                    models.CharField(blank=True, max_length=18, null=True, unique=True),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_number",
                                message="Must be a 10-digit number",
                                regex="^[0-9]{10}$",
                            )
                        ],
                    ),
                ),
                ("entity_info_is_visible", models.BooleanField()),
                (
                    "entity_info_alignment",
                    models.CharField(
                        choices=[("LT", "LEFT"), ("RT", "RIGHT")],
                        default="LT",
                        max_length=2,
                    ),
                ),
                ("entity_name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=250)),
                ("entity_phone_number1", models.CharField(max_length=10, null=True)),
                (
                    "entity_phone_number2",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("entity_timing_is_visible", models.BooleanField()),
                ("entity_startime", models.TimeField()),
                ("entity_endtime", models.TimeField()),
                ("doctor_signature_is_visible", models.BooleanField()),
                (
                    "doctor_info_alignment",
                    models.CharField(
                        choices=[("LT", "LEFT"), ("RT", "RIGHT")],
                        default="LT",
                        max_length=2,
                    ),
                ),
                (
                    "signature_line_1",
                    models.ImageField(
                        blank=True, null=True, upload_to="signatures_line1/"
                    ),
                ),
                (
                    "signature_line_2",
                    models.ImageField(
                        blank=True, null=True, upload_to="signatures_line2/"
                    ),
                ),
                (
                    "doctor_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
