# Generated by Django 4.2.7 on 2024-04-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prescription_setting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescriptionsetting",
            name="signature_line_1",
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="prescriptionsetting",
            name="signature_line_2",
            field=models.TextField(max_length=100, null=True),
        ),
    ]
