# Generated by Django 4.2.7 on 2024-04-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "prescription_setting",
            "0002_alter_prescriptionsetting_signature_line_1_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescriptionsetting",
            name="doctor_info_alignment",
            field=models.CharField(
                choices=[("LT", "LEFT"), ("RT", "RIGHT"), ("MD", "MIDDLE")],
                default="LT",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="prescriptionsetting",
            name="entity_info_alignment",
            field=models.CharField(
                choices=[("LT", "LEFT"), ("RT", "RIGHT"), ("MD", "MIDDLE")],
                default="LT",
                max_length=2,
            ),
        ),
    ]
