# Generated by Django 4.2.7 on 2023-11-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('HP', 'Hospital'), ('CC', 'Clinic'), ('PC', 'Polyclinic')], default='CC', max_length=2)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(max_length=100)),
                ('phone_number1', models.CharField(max_length=10)),
                ('phone_number2', models.CharField(max_length=10)),
                ('aadhar', models.CharField(max_length=16, unique=True)),
                ('address', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=30)),
                ('postal_code', models.CharField(blank=True, max_length=6)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['-created'], name='entity_enti_created_945a15_idx')],
            },
        ),
    ]
