# Generated by Django 4.2.7 on 2023-11-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entity',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
