# Generated by Django 4.2.7 on 2023-11-30 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity_type', '0001_initial'),
        ('entity', '0002_alter_entity_id_alter_entity_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entity_type.entitytype'),
        ),
    ]
