# Generated by Django 4.2.7 on 2023-12-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0003_alter_entity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='phone_number2',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='entity',
            name='website',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
