# Generated by Django 4.2.7 on 2023-12-29 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0004_alter_entity_phone_number2_alter_entity_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='aadhar',
        ),
    ]
