# Generated by Django 4.2.7 on 2024-04-03 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("entity_type", "0002_alter_entitytype_name"),
        ("entity", "0005_remove_entity_aadhar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="entity_type.entitytype",
            ),
        ),
    ]
