# Generated by Django 5.0.1 on 2024-01-25 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_user_created_929e5e_idx',
        ),
    ]
