# Generated by Django 4.2.7 on 2024-03-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_user_date_joined_alter_user_last_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
