# Generated by Django 4.2.7 on 2024-03-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_alter_user_last_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_doctor",
            field=models.BooleanField(default=False),
        ),
    ]
