# Generated by Django 4.2.7 on 2024-03-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_user_is_doctor"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_receptionist",
            field=models.BooleanField(default=False),
        ),
    ]
