# Generated by Django 4.2.7 on 2024-03-19 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0008_user_is_receptionist"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="fee",
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=10,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_number",
                        message="Must be a 10-digit number",
                        regex="^[0-9]{10}$",
                    )
                ],
            ),
        ),
    ]
