# Generated by Django 4.2.7 on 2024-04-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0009_user_fee_alter_user_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="fee",
        ),
        migrations.AddField(
            model_name="user",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("ML", "MALE"), ("FL", "FEMALE"), ("OT", "OTHER")],
                default="ML",
                max_length=2,
            ),
        ),
    ]
