# Generated by Django 4.2.7 on 2024-04-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0010_remove_user_fee_user_age_user_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="registration_number",
            field=models.CharField(blank=True, max_length=18, null=True, unique=True),
        ),
    ]
