# Generated by Django 4.2.7 on 2024-04-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0011_user_registration_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="qualifications",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
