# Generated by Django 4.2.7 on 2024-04-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0014_user_profile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="aadhar_pic",
            field=models.ImageField(blank=True, null=True, upload_to="aadhar_cards/"),
        ),
    ]
