# Generated by Django 4.2.7 on 2024-04-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0015_user_aadhar_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
    ]
