# Generated by Django 4.2.7 on 2024-01-31 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('CR', 'CREATED'), ('IP', 'IN_PROGRESS'), ('CN', 'CANCELLED'), ('PP', 'POSTPONED'), ('CL', 'CLOSED')], default='CR', max_length=2)),
                ('doctor_id', models.IntegerField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=50)),
                ('updated_by', models.CharField(blank=True, max_length=50)),
                ('next_appointment', models.DateTimeField(blank=True, null=True)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('fee_paid', models.BooleanField(default=False)),
                ('appointment_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appointment.appointment')),
            ],
            options={
                'ordering': ['created'],
                'indexes': [models.Index(fields=['created'], name='consultatio_created_2566ee_idx')],
            },
        ),
    ]
