# Generated by Django 4.2.7 on 2024-02-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultation", "0002_consultation_diagnosis_consultation_finding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultation",
            name="status",
            field=models.CharField(
                choices=[("CR", "CREATED"), ("CN", "CANCELLED"), ("CL", "CLOSED")],
                default="CR",
                max_length=2,
            ),
        ),
    ]
