# Generated by Django 4.2.7 on 2024-02-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultation", "0004_alter_consultation_appointment_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultation",
            name="medicine_fingerprint",
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="consultation",
            name="symptom_fingerprint",
            field=models.TextField(max_length=255, null=True),
        ),
    ]
