# Generated by Django 4.2.7 on 2024-02-28 11:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("consultation", "0005_consultation_medicine_fingerprint_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consultation",
            name="medicine_fingerprint",
        ),
        migrations.RemoveField(
            model_name="consultation",
            name="symptom_fingerprint",
        ),
    ]
