# Generated by Django 4.2.7 on 2024-03-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultation", "0006_remove_consultation_medicine_fingerprint_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultation",
            name="diagnosis",
            field=models.TextField(max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name="consultation",
            name="finding",
            field=models.TextField(blank=True, max_length=350, null=True),
        ),
    ]
