# Generated by Django 4.2.7 on 2024-04-27 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("refer_doctor", "0001_initial"),
        ("consultation", "0007_alter_consultation_diagnosis_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultation",
            name="refer_doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="refer_doctor.referdoctor",
            ),
        ),
    ]
