# Generated by Django 4.2.7 on 2024-04-27 16:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("consultation", "0008_consultation_refer_doctor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="consultation",
            old_name="refer_doctor",
            new_name="refer_doctor_id",
        ),
    ]
