# Generated by Django 4.2.7 on 2024-04-01 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("procedure", "0001_initial"),
        ("user_specialization_procedure_mapping", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userspecializationproceduremapping",
            name="procedure_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="procedure.procedure",
            ),
        ),
    ]
