# Generated by Django 4.2.7 on 2024-04-01 13:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("specialization", "0001_initial"),
        (
            "user_specialization_procedure_mapping",
            "0002_alter_userspecializationproceduremapping_procedure_id",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userspecializationproceduremapping",
            unique_together={("user_id", "specialization_id")},
        ),
    ]
